import { getTemplateBySlug } from "@/lib/templates/catalog";
import { renderTemplateThumbnail } from "@/lib/templates/thumbnail";

/**
 * Serves a template's preview image.
 *
 * The SVG is generated deterministically from the template definition, so
 * it can be cached hard and forever at the edge — the only way the bytes
 * change is a code deploy, which invalidates the build anyway.
 */
export async function GET(_req: Request, { params }: { params: { slug: string } }) {
  const template = getTemplateBySlug(params.slug);

  if (!template) {
    // A 404 with an empty body would render as a broken image. A neutral
    // placeholder keeps the grid intact if a slug is ever mistyped.
    return new Response(PLACEHOLDER_SVG, {
      status: 404,
      headers: { "Content-Type": "image/svg+xml; charset=utf-8", "Cache-Control": "public, max-age=60" },
    });
  }

  return new Response(renderTemplateThumbnail(template), {
    headers: {
      "Content-Type": "image/svg+xml; charset=utf-8",
      "Cache-Control": "public, max-age=31536000, immutable",
      // The SVG is generated by us and contains no script, but the header
      // costs nothing and stops any future change from becoming an XSS
      // vector if one of these is ever served from the app's own origin
      // and opened directly.
      "Content-Security-Policy": "default-src 'none'; style-src 'unsafe-inline'",
      "X-Content-Type-Options": "nosniff",
    },
  });
}

const PLACEHOLDER_SVG = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 400" width="640" height="400" role="img" aria-label="Preview unavailable"><rect width="640" height="400" fill="#0F1014"/><rect x="0.5" y="0.5" width="639" height="399" fill="none" stroke="#272A33"/><text x="320" y="205" text-anchor="middle" font-family="system-ui,sans-serif" font-size="15" fill="#565C6B">Preview unavailable</text></svg>`;
