import { NextResponse } from "next/server";
import JSZip from "jszip";
import { createClient } from "@/lib/supabase/server";
import { canUseFeature } from "@/lib/credits";
import { checkRateLimit, globalRateLimitStore } from "@/lib/rate-limit";
import { reportError } from "@/lib/error-reporting";

const MAX_BYTES = 8 * 1024 * 1024;
const MAX_FILES = 250;
const MAX_FILE_BYTES = 512 * 1024;
const ALLOWED_EXT = /\.(tsx?|jsx?|json|css|scss|md|txt|html|svg|xml|yaml|yml|env\.example)$/i;
const IGNORED = /(^|\/)(node_modules|\.git|dist|build|\.next|coverage)(\/|$)/;
function safePath(input: string) { const normalized=input.replace(/\\/g,"/"); if(!normalized||normalized.startsWith("/")||normalized.includes("..")||normalized.includes("\0")) return null; const p=normalized.replace(/^\/+/,""); return p; }
async function readZip(buffer:ArrayBuffer){ if(buffer.byteLength>MAX_BYTES) throw new Error("ZIP is too large. Maximum size is 8 MB."); const zip=await JSZip.loadAsync(buffer,{checkCRC32:true}); const files:{path:string;content:string}[]=[]; for(const [raw,entry] of Object.entries(zip.files)){ if(files.length>=MAX_FILES) throw new Error("ZIP contains too many files. Maximum is 250."); if(entry.dir||IGNORED.test(raw)) continue; const path=safePath(raw); if(!path||!ALLOWED_EXT.test(path)) continue; const data=await entry.async("uint8array"); if(data.byteLength>MAX_FILE_BYTES) continue; files.push({path,content:new TextDecoder().decode(data)}); } if(!files.length) throw new Error("No supported source files were found in the ZIP."); return files; }
export async function POST(req:Request){ const supabase=createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user)return NextResponse.json({error:"Not authenticated"},{status:401}); const rate=checkRateLimit(globalRateLimitStore,`import:${user.id}`,{limit:10,windowMs:60*60*1000}); if(!rate.allowed)return NextResponse.json({error:"Too many import attempts. Try again later."},{status:429}); const [{data:profile},{data:subscription}]=await Promise.all([supabase.from("users").select("role").eq("id",user.id).single(),supabase.from("subscriptions").select("plan, credits_remaining").eq("user_id",user.id).single()]); if(!profile||!subscription)return NextResponse.json({error:"Account not fully provisioned"},{status:500}); const gate=canUseFeature({role:profile.role,plan:subscription.plan,creditsRemaining:subscription.credits_remaining},"importAndExtendApp"); if(!gate.allowed)return NextResponse.json({error:gate.message,reason:gate.reason},{status:403}); try{ const form=await req.formData(); const file=form.get("file"); const githubUrl=String(form.get("githubUrl")||"").trim(); let buffer:ArrayBuffer; let source:"zip"|"github"="zip"; let ref="uploaded-zip"; if(file instanceof File){ buffer=await file.arrayBuffer(); } else if(githubUrl){ const match=githubUrl.match(/^https:\/\/github\.com\/([A-Za-z0-9_.-]+)\/([A-Za-z0-9_.-]+)(?:\/tree\/[^/]+)?\/?$/); if(!match)return NextResponse.json({error:"Use a public GitHub repository URL such as https://github.com/owner/repo."},{status:400}); const [,owner,repo]=match; const cleanRepo=repo.replace(/\.git$/,""); const res=await fetch(`https://api.github.com/repos/${owner}/${cleanRepo}/zipball`,{headers:{Accept:"application/vnd.github+json","User-Agent":"Appo"}}); if(!res.ok)return NextResponse.json({error:"GitHub repository could not be downloaded. Make sure it is public."},{status:400}); const len=Number(res.headers.get("content-length")||0); if(len>MAX_BYTES)return NextResponse.json({error:"GitHub repository ZIP exceeds the 8 MB import limit."},{status:413}); buffer=await res.arrayBuffer(); source="github"; ref=`${owner}/${cleanRepo}`; } else return NextResponse.json({error:"Upload a ZIP file or provide a GitHub repository URL."},{status:400}); const files=await readZip(buffer); return NextResponse.json({source,ref,files,fileCount:files.length}); }catch(err){reportError(err,{route:"/api/import",userId:user.id});return NextResponse.json({error:err instanceof Error?err.message:"Import failed."},{status:400});} }
